/**
 * Template manifest — SHA-256 hash map of every installed kit file.
 *
 * Generated by `mdpi init` after copying the kit into a project's .pi/.
 * Used by `mdpi upgrade` (future) to detect user-modified files:
 *   - "unmodified" → file matches template hash, safe to overwrite on upgrade
 *   - "modified"   → user edited it, preserve on upgrade
 *   - "unknown"    → not a template file (user-added) or no manifest present
 *
 * Ported from OpenCodeKit's utils/manifest.ts (paradigm-agnostic — file/hash
 * ops only, no OpenCode-specific coupling).
 */
import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

export interface TemplateManifest {
  version: string;
  createdAt: string;
  files: Record<string, string>; // relative path → SHA-256 hash
  /** Installed category subset from `mdpi init --only` (sorted). null/absent = full install.
   *  Used by `mdpi upgrade` to avoid pulling in categories the user excluded. */
  categories?: string[] | null;
}

export const MANIFEST_FILE = ".template-manifest.json";

/** Compute SHA-256 hash of a file's content. */
export function hashFile(filePath: string): string {
  return createHash("sha256").update(readFileSync(filePath, "utf-8")).digest("hex");
}

/** Compute SHA-256 hash of an in-memory string. */
export function hashContent(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

/** Walk a directory recursively → {relativePath: sha256}. */
export function buildManifestFromDir(
  dir: string,
  skipDirs: string[] = ["node_modules", ".git", "dist", "coverage", ".next", ".turbo"],
): Record<string, string> {
  const files: Record<string, string> = {};

  function walk(currentDir: string): void {
    for (const entry of readdirSync(currentDir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        if (skipDirs.includes(entry.name)) continue;
        walk(join(currentDir, entry.name));
      } else if (entry.isFile()) {
        if (entry.name === MANIFEST_FILE) continue;
        const fullPath = join(currentDir, entry.name);
        files[relative(dir, fullPath)] = hashFile(fullPath);
      }
    }
  }

  walk(dir);
  return files;
}

/** Generate + write the manifest into a kit directory.
 *  `categories` records an `--only` subset so `mdpi upgrade` can avoid re-adding
 *  excluded categories; pass null/omit for a full install. */
export function generateManifest(
  piDir: string,
  version: string,
  categories: string[] | null = null,
): TemplateManifest {
  const manifest: TemplateManifest = {
    version,
    createdAt: new Date().toISOString(),
    files: buildManifestFromDir(piDir),
    categories: categories ?? null,
  };
  writeFileSync(join(piDir, MANIFEST_FILE), JSON.stringify(manifest, null, 2));
  return manifest;
}

/** Load an existing manifest, or null if none. */
export function loadManifest(piDir: string): TemplateManifest | null {
  const manifestPath = join(piDir, MANIFEST_FILE);
  if (!existsSync(manifestPath)) return null;
  try {
    return JSON.parse(readFileSync(manifestPath, "utf-8")) as TemplateManifest;
  } catch {
    return null;
  }
}

/** Has the user modified a template file since install? */
export function fileModificationStatus(
  filePath: string,
  relativePath: string,
  manifest: TemplateManifest | null,
): "unmodified" | "modified" | "unknown" {
  if (!manifest) return "unknown";

  const templateHash = manifest.files[relativePath];
  if (!templateHash) return "unknown"; // not a template file
  if (!existsSync(filePath)) return "unmodified"; // deleted → treat as unmodified

  return hashFile(filePath) === templateHash ? "unmodified" : "modified";
}